[package]
name = "autocompletion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "*"
libc = "*"
env_logger = "*"
log = "*"
